export const TAGSVIEW_ADD_TAG = 'TAGSVIEW_ADD_TAG'
export const TAGSVIEW_DELETE_TAG = 'TAGSVIEW_DELETE_TAG'
export const TAGSVIEW_EMPTY_TAGLIST = 'TAGSVIEW_EMPTY_TAGLIST'
export const TAGSVIEW_CLOSE_OTHER_TAGS = 'TAGSVIEW_CLOSE_OTHER_TAGS'
